url: "https://kavishdevar.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Kavish's Website" # the name of your site, e.g. ACME Corp.
repository: "kavishdevar/kavishdevar.github.io" # the GitHub repository for your site, e.g. username/repo

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true

plugins:
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"

collections:
  projects:
    output: true
  holiday-homeworks:
    output: true
  tools:
    output: true
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

exclude:
  - bower_components
  - Gemfile
  

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

liquid:
  error_mode: strict
  strict_filters: true

timezone: Asia/Kolkata