url: "https://kavishdevar.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Kavish's Website" # the name of your site, e.g. ACME Corp.
